language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pinggo/react-test -f ./clienter/Dockerfile.dev ./clienter

script:
  - docker run -e CI=true pinggo/react-test npm test -- --coverage


after_success:
  - docker build -t pinggo/multi-client ./clienter
  - docker build -t pinggo/multi-nginx ./nginx
  - docker build -t pinggo/multi-server ./server
  - docker build -t pinggo/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push pinggo/multi-clienter
  - docker push pinggo/multi-nginx
  - docker push pinggo/multi-server
  - docker push pinggo/multi-worker

