language: node_js 
sudo: required
services:
  - docker

before_install:
  - docker build -t docker20208888/react-test -f ./clienter/Dockerfile.dev ./clienter

script:
  - docker run -e CI=true docker20208888/react-test npm test


after_success:
  - docker build -t docker20208888/multi-client ./clienter
  - docker build -t docker20208888/multi-nginx ./nginx
  - docker build -t docker20208888/multi-server ./server
  - docker build -t docker20208888/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push docker20208888/multi-clienter
  - docker push docker20208888/multi-nginx
  - docker push docker20208888/multi-server
  - docker push docker20208888/multi-worker

